/* Generated by gbrecomp from Legend of Zelda, The - Oracle of seasons (USA) */
#include "Legend_of_Zelda__The___Oracle_of_seasons__USA__internal.h"

/* Shared body at 1f:41bb */
static void body_1f_41bb(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x41bb: goto loc_1f_41bb;
        case 0x41bc: goto pc_41bc;
        default: break;
    }

loc_1f_41bb:
    /* INC BC */
    /* 1f:41bb */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x41bc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_41bc:
    /* 1f:41bc */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_41bb(GBContext* ctx) {
    body_1f_41bb(ctx);
}

/* Shared body at 1f:4234 */
static void body_1f_4234(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4234: goto loc_1f_4234;
        case 0x4237: goto pc_4237;
        case 0x4238: goto loc_1f_4238;
        case 0x4239: goto pc_4239;
        case 0x423a: goto pc_423a;
        case 0x423b: goto loc_1f_423b;
        case 0x423c: goto pc_423c;
        case 0x423e: goto loc_1f_423e;
        case 0x423f: goto pc_423f;
        case 0x4240: goto pc_4240;
        case 0x4241: goto loc_1f_4241;
        case 0x4242: goto pc_4242;
        case 0x4245: goto pc_4245;
        case 0x4248: goto pc_4248;
        default: break;
    }

loc_1f_4234:
    /* LD HL,$5520 */
    /* 1f:4234 */     ctx->hl = 0x5520;
    ctx->pc = 0x4237;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_4237:
    /* 1f:4237 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4238;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4238:
    /* LD H,L */
    /* 1f:4238 */     ctx->h = ctx->l;
    ctx->pc = 0x4239;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4239:
    /* 1f:4239 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x423a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,D */
pc_423a:
    /* 1f:423a */     ctx->l = ctx->d;
    ctx->pc = 0x423b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_423b:
    /* INC BC */
    /* 1f:423b */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x423c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR 3 */
pc_423c:
    /* 1f:423c */     gbrt_timed_jump(ctx, 0x4241, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_1f_4241;
    if (ctx->single_step_mode) return;
loc_1f_423e:
    /* OR B */
    /* 1f:423e */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x423f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_423f:
    /* 1f:423f */     ctx->h = ctx->c;
    ctx->pc = 0x4240;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_4240:
    /* 1f:4240 */     ctx->l = ctx->c;
    ctx->pc = 0x4241;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4241:
    /* LD H,H */
    /* 1f:4241 */     ctx->h = ctx->h;
    ctx->pc = 0x4242;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$4202 */
pc_4242:
    /* 1f:4242 */     ctx->bc = 0x4202;
    ctx->pc = 0x4245;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0200 */
pc_4245:
    /* 1f:4245 */     ctx->hl = 0x0200;
    ctx->pc = 0x4248;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_4248:
    /* 1f:4248 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_4234(GBContext* ctx) {
    body_1f_4234(ctx);
}

void func_1f_4238(GBContext* ctx) {
    body_1f_4234(ctx);
}

void func_1f_423b(GBContext* ctx) {
    body_1f_4234(ctx);
}

void func_1f_423e(GBContext* ctx) {
    body_1f_4234(ctx);
}

void func_1f_4241(GBContext* ctx) {
    body_1f_4234(ctx);
}

/* Shared body at 1f:4244 */
static void body_1f_4244(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4244: goto loc_1f_4244;
        case 0x4245: goto pc_4245;
        case 0x4248: goto pc_4248;
        default: break;
    }

loc_1f_4244:
    /* LD B,D */
    /* 1f:4244 */     ctx->b = ctx->d;
    ctx->pc = 0x4245;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0200 */
pc_4245:
    /* 1f:4245 */     ctx->hl = 0x0200;
    ctx->pc = 0x4248;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_4248:
    /* 1f:4248 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_4244(GBContext* ctx) {
    body_1f_4244(ctx);
}

/* Shared body at 1f:4247 */
static void body_1f_4247(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4247: goto loc_1f_4247;
        case 0x4248: goto pc_4248;
        default: break;
    }

loc_1f_4247:
    /* LD (BC),A */
    /* 1f:4247 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4248;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_4248:
    /* 1f:4248 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_4247(GBContext* ctx) {
    body_1f_4247(ctx);
}

/* Shared body at 1f:42a3 */
static void body_1f_42a3(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x42a3: goto loc_1f_42a3;
        case 0x42a4: goto pc_42a4;
        case 0x42a5: goto loc_1f_42a5;
        case 0x42a6: goto loc_1f_42a6;
        case 0x42a7: goto pc_42a7;
        case 0x42a8: goto loc_1f_42a8;
        case 0x42a9: goto pc_42a9;
        case 0x42aa: goto pc_42aa;
        case 0x42ab: goto loc_1f_42ab;
        case 0x42ae: goto pc_42ae;
        case 0x42af: goto pc_42af;
        default: break;
    }

loc_1f_42a3:
    /* INC B */
    /* 1f:42a3 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x42a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB L */
pc_42a4:
    /* 1f:42a4 */     gb_sub8(ctx, ctx->l);
    ctx->pc = 0x42a5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42a5:
    /* LD L,$20 */
    /* 1f:42a5 */     ctx->l = 0x20;
    ctx->pc = 0x42a7;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_42a7:
    /* 1f:42a7 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42a8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_1f_42a8; /* fallthrough */
loc_1f_42a6:
    /* JR NZ,3 */
    /* 1f:42a6 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x42ab, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_42ab;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x42a8, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42a8:
    /* ADC A,L */
    /* 1f:42a8 */     gb_adc8(ctx, ctx->l);
    ctx->pc = 0x42a9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_42a9:
    /* 1f:42a9 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x42aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DI */
pc_42aa:
    /* 1f:42aa */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x42ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42ab:
    /* LD BC,$ac03 */
    /* 1f:42ab */     ctx->bc = GB_ERAM_BASE + 0x0c03;
    ctx->pc = 0x42ae;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_42ae:
    /* 1f:42ae */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x42af;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_42af:
    /* 1f:42af */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x42b0 in bank 31 */
    return;
}

void func_1f_42a3(GBContext* ctx) {
    body_1f_42a3(ctx);
}

void func_1f_42a5(GBContext* ctx) {
    body_1f_42a3(ctx);
}

void func_1f_42a6(GBContext* ctx) {
    body_1f_42a3(ctx);
}

void func_1f_42a8(GBContext* ctx) {
    body_1f_42a3(ctx);
}

/* Shared body at 1f:42bb */
static void body_1f_42bb(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x42bb: goto loc_1f_42bb;
        case 0x42bc: goto pc_42bc;
        case 0x42bd: goto pc_42bd;
        case 0x42c0: goto pc_42c0;
        case 0x42c1: goto pc_42c1;
        case 0x42c3: goto loc_1f_42c3;
        case 0x42c5: goto pc_42c5;
        case 0x42c6: goto loc_1f_42c6;
        case 0x42c9: goto pc_42c9;
        case 0x42ca: goto pc_42ca;
        case 0x42cb: goto pc_42cb;
        case 0x42cc: goto pc_42cc;
        case 0x42cd: goto pc_42cd;
        case 0x42ce: goto pc_42ce;
        case 0x42cf: goto pc_42cf;
        case 0x42d0: goto loc_1f_42d0;
        case 0x42d1: goto pc_42d1;
        case 0x42d2: goto pc_42d2;
        case 0x42d3: goto pc_42d3;
        case 0x42d4: goto loc_1f_42d4;
        case 0x42d5: goto pc_42d5;
        case 0x42d6: goto pc_42d6;
        case 0x42d7: goto pc_42d7;
        case 0x42da: goto loc_1f_42da;
        case 0x42db: goto pc_42db;
        case 0x42dc: goto pc_42dc;
        case 0x42dd: goto pc_42dd;
        case 0x42de: goto pc_42de;
        case 0x42df: goto pc_42df;
        case 0x42e1: goto loc_1f_42e1;
        case 0x42e4: goto pc_42e4;
        case 0x42e5: goto loc_1f_42e5;
        case 0x42e6: goto pc_42e6;
        case 0x42e7: goto pc_42e7;
        case 0x42e8: goto pc_42e8;
        case 0x42eb: goto pc_42eb;
        case 0x42ec: goto pc_42ec;
        case 0x42ed: goto pc_42ed;
        case 0x42ee: goto pc_42ee;
        case 0x42f0: goto pc_42f0;
        case 0x42f1: goto pc_42f1;
        case 0x42f2: goto pc_42f2;
        case 0x42f3: goto pc_42f3;
        case 0x42f4: goto pc_42f4;
        case 0x42f5: goto pc_42f5;
        case 0x42f6: goto pc_42f6;
        case 0x42f7: goto pc_42f7;
        case 0x42f8: goto pc_42f8;
        case 0x42fa: goto loc_1f_42fa;
        case 0x42fc: goto pc_42fc;
        case 0x42fd: goto loc_1f_42fd;
        case 0x4300: goto loc_1f_4300;
        case 0x4301: goto loc_1f_4301;
        case 0x4302: goto loc_1f_4302;
        case 0x4303: goto pc_4303;
        case 0x4304: goto loc_1f_4304;
        case 0x4305: goto loc_1f_4305;
        case 0x4306: goto pc_4306;
        case 0x4307: goto pc_4307;
        case 0x430a: goto loc_1f_430a;
        case 0x430d: goto pc_430d;
        case 0x430e: goto pc_430e;
        case 0x4310: goto pc_4310;
        case 0x4311: goto pc_4311;
        case 0x4312: goto pc_4312;
        case 0x4313: goto pc_4313;
        case 0x4314: goto pc_4314;
        case 0x4315: goto pc_4315;
        default: break;
    }

loc_1f_42bb:
    /* LD (HL),D */
    /* 1f:42bb */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x42bc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_42bc:
    /* 1f:42bc */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x42bd;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$8904 */
pc_42bd:
    /* 1f:42bd */     ctx->bc = GB_VRAM_BASE + 0x0904;
    ctx->pc = 0x42c0;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_42c0:
    /* 1f:42c0 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x42c1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,3 */
pc_42c1:
    /* 1f:42c1 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x42c6, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x42c3, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42c3:
    /* ADD SP,5 */
    /* 1f:42c3 */     gbrt_timed_add_sp(ctx, 0x42c4);
    ctx->pc = 0x42c5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_42c5:
    /* 1f:42c5 */     gb_rla(ctx);
    ctx->pc = 0x42c6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42c6:
    /* LD BC,$9403 */
    /* 1f:42c6 */     ctx->bc = GB_VRAM_BASE + 0x1403;
    ctx->pc = 0x42c9;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_42c9:
    /* 1f:42c9 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x42ca;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_42ca:
    /* 1f:42ca */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42cb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_42cb:
    /* 1f:42cb */     ctx->d = ctx->a;
    ctx->pc = 0x42cc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_42cc:
    /* 1f:42cc */     ctx->l = ctx->a;
    ctx->pc = 0x42cd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_42cd:
    /* 1f:42cd */     ctx->l = ctx->a;
    ctx->pc = 0x42ce;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_42ce:
    /* 1f:42ce */     ctx->h = ctx->h;
    ctx->pc = 0x42cf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_42cf:
    /* 1f:42cf */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42d0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42d0:
    /* DEC SP */
    /* 1f:42d0 */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x42d1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_42d1:
    /* 1f:42d1 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42d2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_42d2:
    /* 1f:42d2 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x42d3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_42d3:
    /* 1f:42d3 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x42d4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42d4:
    /* NOP */
    /* 1f:42d4 */     /* NOP */
    ctx->pc = 0x42d5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_42d5:
    /* 1f:42d5 */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x42d6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_42d6:
    /* 1f:42d6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x42d7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NZ,$013f */
pc_42d7:
    /* 1f:42d7 */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0x13f, 0x42da);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x42da, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42da:
    /* INC BC */
    /* 1f:42da */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42db;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP E */
pc_42db:
    /* 1f:42db */     gb_cp8(ctx, ctx->e);
    ctx->pc = 0x42dc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_42dc:
    /* 1f:42dc */     ctx->l = ctx->h;
    ctx->pc = 0x42dd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_42dd:
    /* 1f:42dd */     ctx->l = ctx->c;
    ctx->pc = 0x42de;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_42de:
    /* 1f:42de */     ctx->h = ctx->l;
    ctx->pc = 0x42df;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_42df:
    /* 1f:42df */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x42e5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x42e1, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42e1:
    /* LD SP,$012c */
    /* 1f:42e1 */     ctx->sp = 0x012c;
    ctx->pc = 0x42e4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_42e4:
    /* 1f:42e4 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x42e5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42e5:
    /* SBC A,H */
    /* 1f:42e5 */     gb_sbc8(ctx, ctx->h);
    ctx->pc = 0x42e6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_42e6:
    /* 1f:42e6 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x42e7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_42e7:
    /* 1f:42e7 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x42e8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$032c */
pc_42e8:
    /* 1f:42e8 */     ctx->bc = 0x032c;
    ctx->pc = 0x42eb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_42eb:
    /* 1f:42eb */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x42ec;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_42ec:
    /* 1f:42ec */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x42ed;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,(HL) */
pc_42ed:
    /* 1f:42ed */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x42ee;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$01 */
pc_42ee:
    /* 1f:42ee */     ctx->l = 0x01;
    ctx->pc = 0x42f0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_42f0:
    /* 1f:42f0 */     gb_rlca(ctx);
    ctx->pc = 0x42f1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_42f1:
    /* 1f:42f1 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x42f2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_42f2:
    /* 1f:42f2 */     ctx->d = ctx->e;
    ctx->pc = 0x42f3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_42f3:
    /* 1f:42f3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x42f4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_42f4:
    /* 1f:42f4 */     ctx->h = ctx->c;
    ctx->pc = 0x42f5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_42f5:
    /* 1f:42f5 */     ctx->l = ctx->l;
    ctx->pc = 0x42f6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_42f6:
    /* 1f:42f6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x42f7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_42f7:
    /* 1f:42f7 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x42f8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,3 */
pc_42f8:
    /* 1f:42f8 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x42fd, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x42fa, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42fa:
    /* ADD SP,5 */
    /* 1f:42fa */     gbrt_timed_add_sp(ctx, 0x42fb);
    ctx->pc = 0x42fc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_42fc:
    /* 1f:42fc */     gb_rla(ctx);
    ctx->pc = 0x42fd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_42fd:
    /* LD BC,$0309 */
    /* 1f:42fd */     ctx->bc = 0x0309;
    ctx->pc = 0x4300;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4300:
    /* LD (BC),A */
    /* 1f:4300 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4301;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4301:
    /* LD HL,$5204 */
    /* 1f:4301 */     ctx->hl = 0x5204;
    ctx->pc = 0x4304;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_1f_4304; /* fallthrough */
loc_1f_4302:
    /* INC B */
    /* 1f:4302 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4303;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,D */
pc_4303:
    /* 1f:4303 */     ctx->d = ctx->d;
    ctx->pc = 0x4304;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4304:
    /* DEC B */
    /* 1f:4304 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4305;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4305:
    /* OR B */
    /* 1f:4305 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x4306;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_4306:
    /* 1f:4306 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4307;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP NC,$0103 */
pc_4307:
    /* 1f:4307 */     if (!ctx->f_c) {
        gbrt_timed_jump(ctx, 0x103, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x430a, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_430a:
    /* LD BC,$7704 */
    /* 1f:430a */     ctx->bc = 0x7704;
    ctx->pc = 0x430d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_430d:
    /* 1f:430d */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x430e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$03 */
pc_430e:
    /* 1f:430e */     ctx->e = 0x03;
    ctx->pc = 0x4310;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_4310:
    /* 1f:4310 */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x4311;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4311:
    /* 1f:4311 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4312;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,(HL) */
pc_4312:
    /* 1f:4312 */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4313;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4313:
    /* 1f:4313 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4314;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND H */
pc_4314:
    /* 1f:4314 */     gb_and8(ctx, ctx->h);
    ctx->pc = 0x4315;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4315:
    /* 1f:4315 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4316;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4316 in bank 31 */
    return;
}

void func_1f_42bb(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_42d0(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_42d4(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_4300(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_4301(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_4302(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_4304(GBContext* ctx) {
    body_1f_42bb(ctx);
}

void func_1f_4305(GBContext* ctx) {
    body_1f_42bb(ctx);
}

/* Shared body at 1f:4a9b */
static void body_1f_4a9b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4a9b: goto loc_1f_4a9b;
        case 0x4a9c: goto pc_4a9c;
        case 0x4a9d: goto pc_4a9d;
        case 0x4a9e: goto pc_4a9e;
        case 0x4aa0: goto pc_4aa0;
        case 0x4aa1: goto pc_4aa1;
        case 0x4aa3: goto loc_1f_4aa3;
        case 0x4aa4: goto pc_4aa4;
        case 0x4aa5: goto loc_1f_4aa5;
        case 0x4aa6: goto pc_4aa6;
        case 0x4aa7: goto pc_4aa7;
        case 0x4aa8: goto pc_4aa8;
        case 0x4aa9: goto pc_4aa9;
        case 0x4aaa: goto pc_4aaa;
        case 0x4aab: goto pc_4aab;
        default: break;
    }

loc_1f_4a9b:
    /* LD (BC),A */
    /* 1f:4a9b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4a9c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_4a9c:
    /* 1f:4a9c */     ctx->h = ctx->c;
    ctx->pc = 0x4a9d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4a9d:
    /* 1f:4a9d */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4a9e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,$02 */
pc_4a9e:
    /* 1f:4a9e */     gb_sbc8(ctx, 0x02);
    ctx->pc = 0x4aa0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_4aa0:
    /* 1f:4aa0 */     ctx->e = ctx->a;
    ctx->pc = 0x4aa1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,2 */
pc_4aa1:
    /* 1f:4aa1 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4aa5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_4aa5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4aa3, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4aa3:
    /* INC E */
    /* 1f:4aa3 */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x4aa4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6873 */
pc_4aa4:
    /* 1f:4aa4 */     ctx->bc = 0x6873;
    ctx->pc = 0x4aa7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_4aa7:
    /* 1f:4aa7 */     ctx->h = ctx->l;
    ctx->pc = 0x4aa8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4aa8:
    /* 1f:4aa8 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4aa9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_4aa9:
    /* 1f:4aa9 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x4aaa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_4aaa:
    /* 1f:4aaa */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4aab;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_4aab:
    /* 1f:4aab */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4aac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4aac in bank 31 */
    return;
loc_1f_4aa5:
    /* LD (HL),E */
    /* 1f:4aa5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4aa6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_4aa6:
    /* 1f:4aa6 */     ctx->l = ctx->b;
    ctx->pc = 0x4aa7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
    /* 1f:4aa7 */     ctx->h = ctx->l;
    ctx->pc = 0x4aa8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
    /* 1f:4aa8 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4aa9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
    /* 1f:4aa9 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x4aaa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
    /* 1f:4aaa */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4aab;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
    /* 1f:4aab */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4aac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4aac in bank 31 */
    return;
}

void func_1f_4a9b(GBContext* ctx) {
    body_1f_4a9b(ctx);
}

/* Shared body at 1f:4ebb */
static void body_1f_4ebb(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4ebb: goto loc_1f_4ebb;
        case 0x4ebc: goto pc_4ebc;
        case 0x4ebd: goto pc_4ebd;
        case 0x4ebe: goto pc_4ebe;
        case 0x4ec0: goto loc_1f_4ec0;
        case 0x4ec1: goto pc_4ec1;
        case 0x4ec2: goto loc_1f_4ec2;
        case 0x4ec3: goto pc_4ec3;
        case 0x4ec4: goto pc_4ec4;
        case 0x4ec5: goto pc_4ec5;
        case 0x4ec6: goto pc_4ec6;
        case 0x4ec7: goto pc_4ec7;
        case 0x4eca: goto pc_4eca;
        case 0x4ecb: goto pc_4ecb;
        case 0x4ece: goto pc_4ece;
        case 0x4ecf: goto pc_4ecf;
        case 0x4ed1: goto pc_4ed1;
        case 0x4ed2: goto pc_4ed2;
        case 0x4ed4: goto pc_4ed4;
        default: break;
    }

loc_1f_4ebb:
    /* LD H,(HL) */
    /* 1f:4ebb */     gb_tick(ctx, 7);
    ctx->h = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ebc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_4ebc:
    /* 1f:4ebc */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4ebd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH (C),A */
pc_4ebd:
    /* 1f:4ebd */     gb_tick(ctx, 7);
    gb_write8(ctx, GB_IO_BASE + ctx->c, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ebe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,2 */
pc_4ebe:
    /* 1f:4ebe */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4ec2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_4ec2;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4ec0, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_4ec0:
    /* LD C,(HL) */
    /* 1f:4ec0 */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ec1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
pc_4ec1:
    /* 1f:4ec1 */     ctx->l = 0x00;
    ctx->pc = 0x4ec3;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4ec3:
    /* 1f:4ec3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ec4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC SP */
pc_4ec4:
    /* 1f:4ec4 */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x4ec5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_4ec5:
    /* 1f:4ec5 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4ec6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,B */
pc_4ec6:
    /* 1f:4ec6 */     ctx->h = ctx->b;
    ctx->pc = 0x4ec7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1c02 */
pc_4ec7:
    /* 1f:4ec7 */     ctx->bc = 0x1c02;
    ctx->pc = 0x4eca;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_4eca:
    /* 1f:4eca */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x4ecb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6577 */
pc_4ecb:
    /* 1f:4ecb */     ctx->bc = 0x6577;
    ctx->pc = 0x4ece;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4ece:
    /* 1f:4ece */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4ecf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$03 */
pc_4ecf:
    /* 1f:4ecf */     ctx->d = 0x03;
    ctx->pc = 0x4ed1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,D */
pc_4ed1:
    /* 1f:4ed1 */     gb_sbc8(ctx, ctx->d);
    ctx->pc = 0x4ed2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
pc_4ed2:
    /* 1f:4ed2 */     ctx->l = 0x00;
    ctx->pc = 0x4ed4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4ed4:
    /* 1f:4ed4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ed5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4ed5 in bank 31 */
    return;
loc_1f_4ec2:
    /* NOP */
    /* 1f:4ec2 */     /* NOP */
    ctx->pc = 0x4ec3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
    /* 1f:4ec3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ec4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC SP */
    /* 1f:4ec4 */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x4ec5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
    /* 1f:4ec5 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4ec6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,B */
    /* 1f:4ec6 */     ctx->h = ctx->b;
    ctx->pc = 0x4ec7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1c02 */
    /* 1f:4ec7 */     ctx->bc = 0x1c02;
    ctx->pc = 0x4eca;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
    /* 1f:4eca */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x4ecb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6577 */
    /* 1f:4ecb */     ctx->bc = 0x6577;
    ctx->pc = 0x4ece;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
    /* 1f:4ece */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4ecf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$03 */
    /* 1f:4ecf */     ctx->d = 0x03;
    ctx->pc = 0x4ed1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,D */
    /* 1f:4ed1 */     gb_sbc8(ctx, ctx->d);
    ctx->pc = 0x4ed2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
    /* 1f:4ed2 */     ctx->l = 0x00;
    ctx->pc = 0x4ed4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
    /* 1f:4ed4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4ed5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4ed5 in bank 31 */
    return;
}

void func_1f_4ebb(GBContext* ctx) {
    body_1f_4ebb(ctx);
}

/* Shared body at 1f:556c */
static void body_1f_556c(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x556c: goto loc_1f_556c;
        case 0x556d: goto pc_556d;
        case 0x556e: goto pc_556e;
        default: break;
    }

loc_1f_556c:
    /* LD (HL),H */
    /* 1f:556c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x556d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_556d:
    /* 1f:556d */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x556e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_556e:
    /* 1f:556e */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_1f_556f(ctx);
    return;
}

void func_1f_556c(GBContext* ctx) {
    body_1f_556c(ctx);
}

/* Shared body at 1f:5835 */
static void body_1f_5835(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5835: goto loc_1f_5835;
        case 0x5836: goto pc_5836;
        default: break;
    }

loc_1f_5835:
    /* INC BC */
    /* 1f:5835 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5836;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_5836:
    /* 1f:5836 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_5835(GBContext* ctx) {
    body_1f_5835(ctx);
}

/* Shared body at 1f:5994 */
static void body_1f_5994(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5994: goto loc_1f_5994;
        case 0x5997: goto pc_5997;
        case 0x5999: goto loc_1f_5999;
        case 0x599a: goto pc_599a;
        case 0x599d: goto pc_599d;
        case 0x599e: goto loc_1f_599e;
        default: break;
    }

loc_1f_5994:
    /* LD BC,$a502 */
    /* 1f:5994 */     ctx->bc = GB_ERAM_BASE + 0x0502;
    ctx->pc = 0x5997;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,5 */
pc_5997:
    /* 1f:5997 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x599e, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_599e;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5999, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_5999:
    /* LD D,E */
    /* 1f:5999 */     ctx->d = ctx->e;
    ctx->pc = 0x599a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$9403 */
pc_599a:
    /* 1f:599a */     ctx->bc = GB_VRAM_BASE + 0x1403;
    ctx->pc = 0x599d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_599d:
    /* 1f:599d */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x599e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_599e:
    /* RETI */
    /* 1f:599e */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x599f in bank 31 */
    return;
}

void func_1f_5994(GBContext* ctx) {
    body_1f_5994(ctx);
}

/* Shared body at 1f:61c2 */
static void body_1f_61c2(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x61c2: goto loc_1f_61c2;
        case 0x61c3: goto pc_61c3;
        default: break;
    }

loc_1f_61c2:
    /* INC BC */
    /* 1f:61c2 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x61c3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_61c3:
    /* 1f:61c3 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_61c2(GBContext* ctx) {
    body_1f_61c2(ctx);
}

/* Shared body at 1f:6d3b */
static void body_1f_6d3b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6d3b: goto loc_1f_6d3b;
        case 0x6d3c: goto pc_6d3c;
        case 0x6d3d: goto pc_6d3d;
        case 0x6d3e: goto pc_6d3e;
        case 0x6d3f: goto pc_6d3f;
        case 0x6d41: goto loc_1f_6d41;
        case 0x6d42: goto pc_6d42;
        case 0x6d44: goto loc_1f_6d44;
        case 0x6d45: goto pc_6d45;
        default: break;
    }

loc_1f_6d3b:
    /* LD (BC),A */
    /* 1f:6d3b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6d3c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND E */
pc_6d3c:
    /* 1f:6d3c */     gb_and8(ctx, ctx->e);
    ctx->pc = 0x6d3d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6d3d:
    /* 1f:6d3d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6d3e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_6d3e:
    /* 1f:6d3e */     ctx->h = ctx->h;
    ctx->pc = 0x6d3f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,3 */
pc_6d3f:
    /* 1f:6d3f */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x6d44, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_6d44;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6d41, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_6d41:
    /* LD A,D */
    /* 1f:6d41 */     ctx->a = ctx->d;
    ctx->pc = 0x6d42;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
pc_6d42:
    /* 1f:6d42 */     ctx->l = 0x00;
    ctx->pc = 0x6d44;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_6d44:
    /* LD D,H */
    /* 1f:6d44 */     ctx->d = ctx->h;
    ctx->pc = 0x6d45;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6d45:
    /* 1f:6d45 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6d46;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6d46 in bank 31 */
    return;
}

void func_1f_6d3b(GBContext* ctx) {
    body_1f_6d3b(ctx);
}

/* Shared body at 1f:6e72 */
static void body_1f_6e72(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6e72: goto loc_1f_6e72;
        case 0x6e73: goto loc_1f_6e73;
        default: break;
    }

loc_1f_6e72:
    /* INC BC */
    /* 1f:6e72 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6e73;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_6e73:
    /* JP HL */
    /* 1f:6e73 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_6e72(GBContext* ctx) {
    body_1f_6e72(ctx);
}

void func_1f_6e73(GBContext* ctx) {
    body_1f_6e72(ctx);
}

/* Shared body at 1f:6f75 */
static void body_1f_6f75(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6f75: goto loc_1f_6f75;
        case 0x6f76: goto pc_6f76;
        default: break;
    }

loc_1f_6f75:
    /* INC BC */
    /* 1f:6f75 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6f76;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_6f76:
    /* 1f:6f76 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_6f75(GBContext* ctx) {
    body_1f_6f75(ctx);
}

/* Shared body at 1f:6fa5 */
static void body_1f_6fa5(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_1f_6fa5:
    /* JP HL */
    /* 1f:6fa5 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_6fa5(GBContext* ctx) {
    body_1f_6fa5(ctx);
}

/* Shared body at 1f:7194 */
static void body_1f_7194(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7194: goto loc_1f_7194;
        case 0x7195: goto pc_7195;
        default: break;
    }

loc_1f_7194:
    /* INC BC */
    /* 1f:7194 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7195;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_7195:
    /* 1f:7195 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_7194(GBContext* ctx) {
    body_1f_7194(ctx);
}

/* Shared body at 1f:7449 */
static void body_1f_7449(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7449: goto loc_1f_7449;
        case 0x744a: goto pc_744a;
        case 0x744b: goto pc_744b;
        case 0x744c: goto pc_744c;
        case 0x744d: goto pc_744d;
        case 0x744f: goto loc_1f_744f;
        case 0x7450: goto pc_7450;
        case 0x7451: goto pc_7451;
        case 0x7452: goto loc_1f_7452;
        case 0x7454: goto loc_1f_7454;
        case 0x7455: goto pc_7455;
        case 0x7456: goto pc_7456;
        default: break;
    }

loc_1f_7449:
    /* LD (HL),H */
    /* 1f:7449 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x744a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_744a:
    /* 1f:744a */     ctx->l = ctx->a;
    ctx->pc = 0x744b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_744b:
    /* 1f:744b */     ctx->l = ctx->a;
    ctx->pc = 0x744c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_744c:
    /* 1f:744c */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x744d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,3 */
pc_744d:
    /* 1f:744d */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7452, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7452;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x744f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_744f:
    /* OR D */
    /* 1f:744f */     gb_or8(ctx, ctx->d);
    ctx->pc = 0x7450;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_7450:
    /* 1f:7450 */     ctx->h = ctx->a;
    ctx->pc = 0x7451;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_7451:
    /* 1f:7451 */     ctx->l = ctx->a;
    ctx->pc = 0x7452;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7452:
    /* JR NZ,3 */
    /* 1f:7452 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7457, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7457;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7454, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7454:
    /* LD (HL),C */
    /* 1f:7454 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x7455;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_7455:
    /* 1f:7455 */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x7456;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7456:
    /* 1f:7456 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7457;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7457:
    goto loc_1f_7457; /* fallthrough */
}

void func_1f_7449(GBContext* ctx) {
    body_1f_7449(ctx);
}

/* Shared body at 1f:7652 */
static void body_1f_7652(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7652: goto loc_1f_7652;
        case 0x7654: goto pc_7654;
        case 0x7655: goto loc_1f_7655;
        case 0x7656: goto pc_7656;
        case 0x7657: goto pc_7657;
        case 0x7658: goto pc_7658;
        case 0x7659: goto loc_1f_7659;
        case 0x765a: goto pc_765a;
        case 0x765b: goto pc_765b;
        case 0x765c: goto pc_765c;
        case 0x765d: goto pc_765d;
        case 0x765e: goto pc_765e;
        case 0x765f: goto pc_765f;
        case 0x7660: goto pc_7660;
        case 0x7661: goto loc_1f_7661;
        case 0x7662: goto pc_7662;
        case 0x7663: goto pc_7663;
        case 0x7664: goto pc_7664;
        case 0x7665: goto loc_1f_7665;
        case 0x7666: goto pc_7666;
        case 0x7667: goto pc_7667;
        case 0x7668: goto pc_7668;
        case 0x7669: goto loc_1f_7669;
        case 0x766a: goto pc_766a;
        default: break;
    }

loc_1f_7652:
    /* LD C,$c7 */
    /* 1f:7652 */     ctx->c = 0xc7;
    ctx->pc = 0x7654;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_7654:
    /* 1f:7654 */     ctx->c = ctx->h;
    ctx->pc = 0x7655;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7655:
    /* LD L,C */
    /* 1f:7655 */     ctx->l = ctx->c;
    ctx->pc = 0x7656;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* HALT */
pc_7656:
    /* 1f:7656 */     gbrt_execute_halt(ctx, 0x7657, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7657:
    /* 1f:7657 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7658;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND (HL) */
pc_7658:
    /* 1f:7658 */     gb_tick(ctx, 7);
    gb_and8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x7659;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7659:
    /* DEC B */
    /* 1f:7659 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x765a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_765a:
    /* 1f:765a */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x765b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_765b:
    /* 1f:765b */     ctx->h = ctx->l;
    ctx->pc = 0x765c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_765c:
    /* 1f:765c */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x765d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_765d:
    /* 1f:765d */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x765e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_765e:
    /* 1f:765e */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x765f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH (C),A */
pc_765f:
    /* 1f:765f */     gb_tick(ctx, 7);
    gb_write8(ctx, GB_IO_BASE + ctx->c, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7660;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7660:
    /* 1f:7660 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7661;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7661:
    /* ADC A,H */
    /* 1f:7661 */     gb_adc8(ctx, ctx->h);
    ctx->pc = 0x7662;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7662:
    /* 1f:7662 */     ctx->l = ctx->c;
    ctx->pc = 0x7663;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7663:
    /* 1f:7663 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7664;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7664:
    /* 1f:7664 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7665;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7665:
    /* OR H */
    /* 1f:7665 */     gb_or8(ctx, ctx->h);
    ctx->pc = 0x7666;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_7666:
    /* 1f:7666 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7667;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7667:
    /* 1f:7667 */     gb_rrca(ctx);
    ctx->pc = 0x7668;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_7668:
    /* 1f:7668 */     ctx->l = ctx->h;
    ctx->pc = 0x7669;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7669:
    /* DEC B */
    /* 1f:7669 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x766a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_766a:
    /* 1f:766a */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x766b in bank 31 */
    return;
}

void func_1f_7652(GBContext* ctx) {
    body_1f_7652(ctx);
}

void func_1f_7655(GBContext* ctx) {
    body_1f_7652(ctx);
}

void func_1f_7659(GBContext* ctx) {
    body_1f_7652(ctx);
}

void func_1f_7661(GBContext* ctx) {
    body_1f_7652(ctx);
}

void func_1f_7665(GBContext* ctx) {
    body_1f_7652(ctx);
}

void func_1f_7669(GBContext* ctx) {
    body_1f_7652(ctx);
}

/* Shared body at 1f:7753 */
static void body_1f_7753(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7753: goto loc_1f_7753;
        case 0x7754: goto loc_1f_7754;
        default: break;
    }

loc_1f_7753:
    /* INC BC */
    /* 1f:7753 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7754;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7754:
    /* JP HL */
    /* 1f:7754 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_1f_7753(GBContext* ctx) {
    body_1f_7753(ctx);
}

void func_1f_7754(GBContext* ctx) {
    body_1f_7753(ctx);
}

/* Shared body at 1f:7c6e */
static void body_1f_7c6e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7c6e: goto loc_1f_7c6e;
        case 0x7c6f: goto loc_1f_7c6f;
        case 0x7c70: goto pc_7c70;
        case 0x7c71: goto pc_7c71;
        case 0x7c72: goto pc_7c72;
        case 0x7c73: goto pc_7c73;
        case 0x7c74: goto pc_7c74;
        case 0x7c75: goto pc_7c75;
        case 0x7c76: goto pc_7c76;
        case 0x7c77: goto pc_7c77;
        case 0x7c7a: goto pc_7c7a;
        case 0x7c7b: goto pc_7c7b;
        case 0x7c7c: goto pc_7c7c;
        case 0x7c7d: goto pc_7c7d;
        case 0x7c7e: goto pc_7c7e;
        case 0x7c7f: goto pc_7c7f;
        case 0x7c80: goto pc_7c80;
        case 0x7c83: goto pc_7c83;
        case 0x7c84: goto pc_7c84;
        case 0x7c85: goto pc_7c85;
        case 0x7c86: goto pc_7c86;
        case 0x7c87: goto pc_7c87;
        case 0x7c8a: goto loc_1f_7c8a;
        case 0x7c8b: goto pc_7c8b;
        case 0x7c8c: goto loc_1f_7c8c;
        case 0x7c8d: goto pc_7c8d;
        case 0x7c90: goto loc_1f_7c90;
        case 0x7c91: goto pc_7c91;
        case 0x7c92: goto pc_7c92;
        case 0x7c93: goto pc_7c93;
        case 0x7c94: goto pc_7c94;
        case 0x7c95: goto pc_7c95;
        case 0x7c96: goto pc_7c96;
        case 0x7c97: goto pc_7c97;
        case 0x7c98: goto pc_7c98;
        case 0x7c99: goto pc_7c99;
        case 0x7c9a: goto pc_7c9a;
        case 0x7c9b: goto pc_7c9b;
        case 0x7c9c: goto pc_7c9c;
        case 0x7c9d: goto pc_7c9d;
        case 0x7c9e: goto pc_7c9e;
        case 0x7c9f: goto pc_7c9f;
        case 0x7ca0: goto pc_7ca0;
        case 0x7ca1: goto pc_7ca1;
        case 0x7ca2: goto pc_7ca2;
        case 0x7ca3: goto pc_7ca3;
        default: break;
    }

loc_1f_7c6e:
    /* LD L,C */
    /* 1f:7c6e */     ctx->l = ctx->c;
    ctx->pc = 0x7c6f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7c6f:
    /* LD (HL),H */
    /* 1f:7c6f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c70;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7c70:
    /* 1f:7c70 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7c71;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND H */
pc_7c71:
    /* 1f:7c71 */     gb_and8(ctx, ctx->h);
    ctx->pc = 0x7c72;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,(HL) */
pc_7c72:
    /* 1f:7c72 */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c73;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_7c73:
    /* 1f:7c73 */     ctx->l = ctx->a;
    ctx->pc = 0x7c74;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7c74:
    /* 1f:7c74 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7c75;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR D */
pc_7c75:
    /* 1f:7c75 */     gb_or8(ctx, ctx->d);
    ctx->pc = 0x7c76;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DAA */
pc_7c76:
    /* 1f:7c76 */     gb_daa(ctx);
    ctx->pc = 0x7c77;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$4620 */
pc_7c77:
    /* 1f:7c77 */     ctx->hl = 0x4620;
    ctx->pc = 0x7c7a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_7c7a:
    /* 1f:7c7a */     ctx->l = ctx->a;
    ctx->pc = 0x7c7b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7c7b:
    /* 1f:7c7b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c7c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_7c7c:
    /* 1f:7c7c */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7c7d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_7c7d:
    /* 1f:7c7d */     ctx->h = ctx->h;
    ctx->pc = 0x7c7e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7c7e:
    /* 1f:7c7e */     ctx->l = ctx->c;
    ctx->pc = 0x7c7f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7c7f:
    /* 1f:7c7f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c80;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$4120 */
pc_7c80:
    /* 1f:7c80 */     ctx->hl = 0x4120;
    ctx->pc = 0x7c83;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7c83:
    /* 1f:7c83 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c84;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP A */
pc_7c84:
    /* 1f:7c84 */     gb_cp8(ctx, ctx->a);
    ctx->pc = 0x7c85;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7c85:
    /* 1f:7c85 */     /* NOP */
    ctx->pc = 0x7c86;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7c86:
    /* 1f:7c86 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c87;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $7571 */
pc_7c87:
    /* 1f:7c87 */     gbrt_timed_call(ctx, 0x7571, 0x7c8a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_1f_7571(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_1f_7c8a:
    /* LD L,C */
    /* 1f:7c8a */     ctx->l = ctx->c;
    ctx->pc = 0x7c8b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7c8b:
    /* 1f:7c8b */     ctx->h = ctx->l;
    ctx->pc = 0x7c8c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7c8c:
    /* LD (HL),H */
    /* 1f:7c8c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c8d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$7305 */
pc_7c8d:
    /* 1f:7c8d */     ctx->bc = 0x7305;
    ctx->pc = 0x7c90;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7c90:
    /* LD (HL),E */
    /* 1f:7c90 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c91;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7c91:
    /* 1f:7c91 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c92;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7c92:
    /* 1f:7c92 */     ctx->h = ctx->c;
    ctx->pc = 0x7c93;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7c93:
    /* 1f:7c93 */     ctx->l = ctx->c;
    ctx->pc = 0x7c94;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7c94:
    /* 1f:7c94 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c95;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7c95:
    /* 1f:7c95 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c96;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7c96:
    /* 1f:7c96 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c97;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* HALT */
pc_7c97:
    /* 1f:7c97 */     gbrt_execute_halt(ctx, 0x7c98, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD B,L */
pc_7c98:
    /* 1f:7c98 */     ctx->b = ctx->l;
    ctx->pc = 0x7c99;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* HALT */
pc_7c99:
    /* 1f:7c99 */     gbrt_execute_halt(ctx, 0x7c9a, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* DAA */
pc_7c9a:
    /* 1f:7c9a */     gb_daa(ctx);
    ctx->pc = 0x7c9b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7c9b:
    /* 1f:7c9b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c9c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_7c9c:
    /* 1f:7c9c */     ctx->a = ctx->c;
    ctx->pc = 0x7c9d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_7c9d:
    /* 1f:7c9d */     ctx->l = ctx->a;
    ctx->pc = 0x7c9e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7c9e:
    /* 1f:7c9e */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7c9f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7c9f:
    /* 1f:7c9f */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7ca0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND D */
pc_7ca0:
    /* 1f:7ca0 */     gb_and8(ctx, ctx->d);
    ctx->pc = 0x7ca1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_7ca1:
    /* 1f:7ca1 */     ctx->h = ctx->a;
    ctx->pc = 0x7ca2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_7ca2:
    /* 1f:7ca2 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7ca3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_7ca3:
    /* 1f:7ca3 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7ca4 in bank 31 */
    return;
}

void func_1f_7c6e(GBContext* ctx) {
    body_1f_7c6e(ctx);
}

void func_1f_7c6f(GBContext* ctx) {
    body_1f_7c6e(ctx);
}

void func_1f_7c8c(GBContext* ctx) {
    body_1f_7c6e(ctx);
}

void func_1f_7c90(GBContext* ctx) {
    body_1f_7c6e(ctx);
}

/* Shared body at 1f:7ca9 */
static void body_1f_7ca9(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7ca9: goto loc_1f_7ca9;
        case 0x7caa: goto pc_7caa;
        case 0x7cab: goto pc_7cab;
        case 0x7cac: goto pc_7cac;
        case 0x7cad: goto pc_7cad;
        case 0x7cae: goto pc_7cae;
        case 0x7caf: goto pc_7caf;
        case 0x7cb2: goto pc_7cb2;
        case 0x7cb3: goto pc_7cb3;
        case 0x7cb5: goto loc_1f_7cb5;
        case 0x7cb9: goto loc_1f_7cb9;
        case 0x7cba: goto pc_7cba;
        case 0x7cbb: goto pc_7cbb;
        case 0x7cbc: goto pc_7cbc;
        case 0x7cbd: goto pc_7cbd;
        case 0x7cbe: goto pc_7cbe;
        case 0x7cc0: goto loc_1f_7cc0;
        case 0x7cc1: goto pc_7cc1;
        case 0x7cc4: goto loc_1f_7cc4;
        case 0x7cc5: goto pc_7cc5;
        case 0x7cc6: goto pc_7cc6;
        case 0x7cc7: goto pc_7cc7;
        case 0x7cc8: goto loc_1f_7cc8;
        case 0x7cc9: goto loc_1f_7cc9;
        case 0x7cca: goto pc_7cca;
        case 0x7ccb: goto loc_1f_7ccb;
        case 0x7ccc: goto loc_1f_7ccc;
        case 0x7ccf: goto pc_7ccf;
        case 0x7cd0: goto pc_7cd0;
        case 0x7cd1: goto pc_7cd1;
        case 0x7cd2: goto pc_7cd2;
        case 0x7cd3: goto pc_7cd3;
        case 0x7cd5: goto pc_7cd5;
        case 0x7cd6: goto pc_7cd6;
        case 0x7cd7: goto pc_7cd7;
        case 0x7cd8: goto pc_7cd8;
        default: break;
    }

loc_1f_7ca9:
    /* LD (HL),D */
    /* 1f:7ca9 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7caa;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7caa:
    /* 1f:7caa */     ctx->h = ctx->l;
    ctx->pc = 0x7cab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7cab:
    /* 1f:7cab */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cac;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR H */
pc_7cac:
    /* 1f:7cac */     gb_xor8(ctx, ctx->h);
    ctx->pc = 0x7cad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7cad:
    /* 1f:7cad */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7cae;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR L */
pc_7cae:
    /* 1f:7cae */     gb_or8(ctx, ctx->l);
    ctx->pc = 0x7caf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$d905 */
pc_7caf:
    /* 1f:7caf */     ctx->bc = GB_WRAMX_BASE + 0x0905;
    ctx->pc = 0x7cb2;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7cb2:
    /* 1f:7cb2 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cb3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_7cb3:
    /* 1f:7cb3 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7cb9, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7cb9;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7cb5, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7cb5:
    /* JP HL */
    /* 1f:7cb5 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
loc_1f_7cb9:
    /* NOP */
    /* 1f:7cb9 */     /* NOP */
    ctx->pc = 0x7cba;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7cba:
    /* 1f:7cba */     ctx->b = ctx->c;
    ctx->pc = 0x7cbb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_7cbb:
    /* 1f:7cbb */     ctx->a = ctx->c;
    ctx->pc = 0x7cbc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7cbc:
    /* 1f:7cbc */     ctx->h = ctx->l;
    ctx->pc = 0x7cbd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_7cbd:
    /* 1f:7cbd */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x7cbe;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_7cbe:
    /* 1f:7cbe */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7cc4, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7cc4;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7cc0, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7cc0:
    /* PUSH AF */
    /* 1f:7cc0 */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x7cc1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$3d04 */
pc_7cc1:
    /* 1f:7cc1 */     ctx->bc = 0x3d04;
    ctx->pc = 0x7cc4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7cc4:
    /* LD (HL),L */
    /* 1f:7cc4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cc5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7cc5:
    /* 1f:7cc5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cc6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7cc6:
    /* 1f:7cc6 */     ctx->h = ctx->l;
    ctx->pc = 0x7cc7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_7cc7:
    /* 1f:7cc7 */     ctx->h = ctx->h;
    ctx->pc = 0x7cc8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7cc8:
    /* INC BC */
    /* 1f:7cc8 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7cc9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7cc9:
    /* OR B */
    /* 1f:7cc9 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x7cca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7cca:
    /* 1f:7cca */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7ccb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7ccb:
    /* RST $38 */
    /* 1f:7ccb */     gbrt_timed_rst(ctx, 0x38, 0x7ccc);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_1f_7ccc:
    /* LD BC,$6527 */
    /* 1f:7ccc */     ctx->bc = 0x6527;
    ctx->pc = 0x7ccf;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7ccf:
    /* 1f:7ccf */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cd0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7cd0:
    /* 1f:7cd0 */     ctx->h = ctx->l;
    ctx->pc = 0x7cd1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7cd1:
    /* 1f:7cd1 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7cd2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_7cd2:
    /* 1f:7cd2 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7cd3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
pc_7cd3:
    /* 1f:7cd3 */     ctx->l = 0x00;
    ctx->pc = 0x7cd5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_7cd5:
    /* 1f:7cd5 */     ctx->c = ctx->b;
    ctx->pc = 0x7cd6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_7cd6:
    /* 1f:7cd6 */     ctx->l = ctx->a;
    ctx->pc = 0x7cd7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_7cd7:
    /* 1f:7cd7 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7cd8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7cd8:
    /* 1f:7cd8 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7cd9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7cd9 in bank 31 */
    return;
}

void func_1f_7ca9(GBContext* ctx) {
    body_1f_7ca9(ctx);
}

void func_1f_7cc8(GBContext* ctx) {
    body_1f_7ca9(ctx);
}

void func_1f_7cc9(GBContext* ctx) {
    body_1f_7ca9(ctx);
}

void func_1f_7ccb(GBContext* ctx) {
    body_1f_7ca9(ctx);
}

/* Shared body at 1f:7fe6 */
static void body_1f_7fe6(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7fe6: goto loc_1f_7fe6;
        case 0x7fe7: goto pc_7fe7;
        case 0x7fe9: goto loc_1f_7fe9;
        case 0x7fea: goto pc_7fea;
        case 0x7feb: goto loc_1f_7feb;
        case 0x7fed: goto loc_1f_7fed;
        case 0x7fee: goto pc_7fee;
        case 0x7fef: goto pc_7fef;
        case 0x7ff0: goto pc_7ff0;
        case 0x7ff1: goto pc_7ff1;
        case 0x7ff3: goto loc_1f_7ff3;
        case 0x7ff4: goto pc_7ff4;
        case 0x7ff6: goto loc_1f_7ff6;
        case 0x7ff7: goto pc_7ff7;
        case 0x7ff8: goto pc_7ff8;
        case 0x7ff9: goto pc_7ff9;
        case 0x7ffb: goto loc_1f_7ffb;
        case 0x7ffc: goto pc_7ffc;
        case 0x7ffd: goto pc_7ffd;
        case 0x7ffe: goto pc_7ffe;
        case 0x7fff: goto pc_7fff;
        default: break;
    }

loc_1f_7fe6:
    /* LD (HL),E */
    /* 1f:7fe6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fe7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,39 */
pc_7fe7:
    /* 1f:7fe7 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x8010, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7fe9, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7fe9:
    /* DEC B */
    /* 1f:7fe9 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7fea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NC */
pc_7fea:
    /* 1f:7fea */     if (!ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x7feb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7feb:
    /* JR NZ,103 */
    /* 1f:7feb */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x8054, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7fed, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7fed:
    /* DEC B */
    /* 1f:7fed */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7fee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,L */
pc_7fee:
    /* 1f:7fee */     ctx->e = ctx->l;
    ctx->pc = 0x7fef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,D */
pc_7fef:
    /* 1f:7fef */     ctx->h = ctx->d;
    ctx->pc = 0x7ff0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_7ff0:
    /* 1f:7ff0 */     ctx->a = ctx->c;
    ctx->pc = 0x7ff1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,3 */
pc_7ff1:
    /* 1f:7ff1 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ff6, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7ff6;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7ff3, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7ff3:
    /* AND B */
    /* 1f:7ff3 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x7ff4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,5 */
pc_7ff4:
    /* 1f:7ff4 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ffb, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_1f_7ffb;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7ff6, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_1f_7ff6:
    /* SBC A,H */
    /* 1f:7ff6 */     gb_sbc8(ctx, ctx->h);
    ctx->pc = 0x7ff7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7ff7:
    /* 1f:7ff7 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ff8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_7ff8:
    /* 1f:7ff8 */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x7ff9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$7c05 */
pc_7ff9:
    /* 1f:7ff9 */     ctx->bc = 0x7c05;
    ctx->pc = 0x7ffc;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7ffc:
    /* 1f:7ffc */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7ffd;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
pc_7ffd:
    /* 1f:7ffd */     ctx->l = ctx->e;
    ctx->pc = 0x7ffe;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7ffe:
    /* 1f:7ffe */     ctx->h = ctx->c;
    ctx->pc = 0x7fff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7fff:
    /* 1f:7fff */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x8000;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x8000 in bank 31 */
    return;
loc_1f_7ffb:
    /* LD A,H */
    /* 1f:7ffb */     ctx->a = ctx->h;
    ctx->pc = 0x7ffc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
    /* 1f:7ffc */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7ffd;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
    /* 1f:7ffd */     ctx->l = ctx->e;
    ctx->pc = 0x7ffe;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
    /* 1f:7ffe */     ctx->h = ctx->c;
    ctx->pc = 0x7fff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
    /* 1f:7fff */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x8000;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x8000 in bank 31 */
    return;
}

void func_1f_7fe6(GBContext* ctx) {
    body_1f_7fe6(ctx);
}

