/* Generated by gbrecomp from Legend of Zelda, The - Oracle of seasons (USA) */
#include "Legend_of_Zelda__The___Oracle_of_seasons__USA__internal.h"

/* Shared body at 11:4015 */
static void body_11_4015(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4015: goto loc_11_4015;
        case 0x4016: goto loc_11_4016;
        case 0x4017: goto pc_4017;
        case 0x4018: goto loc_11_4018;
        case 0x4019: goto loc_11_4019;
        case 0x401c: goto pc_401c;
        case 0x401d: goto pc_401d;
        case 0x401e: goto loc_11_401e;
        case 0x401f: goto pc_401f;
        case 0x4020: goto loc_11_4020;
        case 0x4021: goto loc_11_4021;
        case 0x4022: goto loc_11_4022;
        case 0x4023: goto pc_4023;
        case 0x4024: goto pc_4024;
        case 0x4025: goto pc_4025;
        case 0x4026: goto loc_11_4026;
        case 0x4027: goto loc_11_4027;
        case 0x4028: goto loc_11_4028;
        case 0x4029: goto pc_4029;
        case 0x402c: goto pc_402c;
        case 0x402d: goto pc_402d;
        case 0x402e: goto loc_11_402e;
        case 0x402f: goto loc_11_402f;
        case 0x4030: goto loc_11_4030;
        case 0x4031: goto pc_4031;
        case 0x4032: goto pc_4032;
        case 0x4033: goto pc_4033;
        case 0x4034: goto pc_4034;
        case 0x4035: goto pc_4035;
        case 0x4036: goto pc_4036;
        case 0x4037: goto loc_11_4037;
        case 0x4038: goto loc_11_4038;
        case 0x4039: goto pc_4039;
        case 0x403a: goto pc_403a;
        case 0x403b: goto pc_403b;
        case 0x403c: goto loc_11_403c;
        case 0x403d: goto pc_403d;
        case 0x403e: goto loc_11_403e;
        case 0x403f: goto pc_403f;
        case 0x4040: goto loc_11_4040;
        case 0x4041: goto loc_11_4041;
        case 0x4042: goto loc_11_4042;
        case 0x4043: goto pc_4043;
        case 0x4044: goto loc_11_4044;
        case 0x4045: goto pc_4045;
        case 0x4046: goto pc_4046;
        case 0x4047: goto pc_4047;
        case 0x4048: goto loc_11_4048;
        case 0x4049: goto pc_4049;
        case 0x404a: goto loc_11_404a;
        case 0x404b: goto loc_11_404b;
        case 0x404c: goto pc_404c;
        case 0x404d: goto pc_404d;
        case 0x404e: goto loc_11_404e;
        case 0x404f: goto pc_404f;
        case 0x4050: goto loc_11_4050;
        case 0x4051: goto pc_4051;
        case 0x4052: goto pc_4052;
        case 0x4054: goto pc_4054;
        case 0x4055: goto loc_11_4055;
        case 0x4056: goto loc_11_4056;
        case 0x4057: goto loc_11_4057;
        case 0x4058: goto loc_11_4058;
        case 0x4059: goto loc_11_4059;
        case 0x405a: goto loc_11_405a;
        case 0x405b: goto pc_405b;
        case 0x405c: goto loc_11_405c;
        case 0x405f: goto loc_11_405f;
        case 0x4060: goto loc_11_4060;
        case 0x4061: goto loc_11_4061;
        case 0x4062: goto pc_4062;
        case 0x4063: goto loc_11_4063;
        case 0x4064: goto pc_4064;
        case 0x4066: goto loc_11_4066;
        case 0x4067: goto pc_4067;
        case 0x406a: goto pc_406a;
        case 0x406b: goto loc_11_406b;
        case 0x406c: goto pc_406c;
        case 0x406d: goto pc_406d;
        case 0x406e: goto pc_406e;
        case 0x406f: goto loc_11_406f;
        case 0x4070: goto pc_4070;
        case 0x4071: goto loc_11_4071;
        case 0x4072: goto pc_4072;
        case 0x4074: goto loc_11_4074;
        case 0x4075: goto pc_4075;
        case 0x4076: goto loc_11_4076;
        case 0x4077: goto loc_11_4077;
        case 0x4078: goto pc_4078;
        case 0x4079: goto pc_4079;
        case 0x407a: goto pc_407a;
        case 0x407b: goto pc_407b;
        case 0x407c: goto pc_407c;
        case 0x407d: goto pc_407d;
        case 0x407f: goto pc_407f;
        case 0x4080: goto loc_11_4080;
        case 0x4081: goto loc_11_4081;
        case 0x4082: goto pc_4082;
        case 0x4083: goto loc_11_4083;
        case 0x4084: goto pc_4084;
        case 0x4086: goto loc_11_4086;
        case 0x4087: goto pc_4087;
        case 0x4088: goto loc_11_4088;
        case 0x4089: goto pc_4089;
        case 0x408a: goto loc_11_408a;
        case 0x408b: goto pc_408b;
        case 0x408c: goto pc_408c;
        case 0x408e: goto pc_408e;
        case 0x4090: goto loc_11_4090;
        case 0x4091: goto pc_4091;
        case 0x4093: goto loc_11_4093;
        case 0x4094: goto pc_4094;
        case 0x4096: goto pc_4096;
        case 0x4097: goto loc_11_4097;
        case 0x4098: goto loc_11_4098;
        case 0x4099: goto loc_11_4099;
        case 0x409a: goto loc_11_409a;
        case 0x409b: goto loc_11_409b;
        case 0x409d: goto pc_409d;
        case 0x409e: goto pc_409e;
        case 0x409f: goto pc_409f;
        case 0x40a0: goto loc_11_40a0;
        case 0x40a1: goto pc_40a1;
        case 0x40a2: goto pc_40a2;
        case 0x40a3: goto loc_11_40a3;
        case 0x40a4: goto pc_40a4;
        case 0x40a6: goto loc_11_40a6;
        case 0x40a7: goto loc_11_40a7;
        case 0x40a8: goto loc_11_40a8;
        case 0x40a9: goto pc_40a9;
        case 0x40ac: goto pc_40ac;
        case 0x40ad: goto loc_11_40ad;
        case 0x40b0: goto loc_11_40b0;
        case 0x40b1: goto loc_11_40b1;
        case 0x40b2: goto pc_40b2;
        case 0x40b3: goto pc_40b3;
        case 0x40b4: goto pc_40b4;
        case 0x40b5: goto pc_40b5;
        case 0x40b6: goto pc_40b6;
        case 0x40b7: goto loc_11_40b7;
        case 0x40b8: goto loc_11_40b8;
        case 0x40b9: goto pc_40b9;
        case 0x40bb: goto loc_11_40bb;
        case 0x40bc: goto pc_40bc;
        case 0x40bd: goto pc_40bd;
        case 0x40be: goto loc_11_40be;
        case 0x40bf: goto loc_11_40bf;
        case 0x40c0: goto loc_11_40c0;
        case 0x40c1: goto pc_40c1;
        case 0x40c2: goto pc_40c2;
        case 0x40c3: goto loc_11_40c3;
        case 0x40c5: goto loc_11_40c5;
        case 0x40c6: goto loc_11_40c6;
        case 0x40c7: goto pc_40c7;
        case 0x40c8: goto pc_40c8;
        case 0x40c9: goto loc_11_40c9;
        case 0x40cb: goto loc_11_40cb;
        case 0x40cc: goto pc_40cc;
        case 0x40cd: goto pc_40cd;
        case 0x40ce: goto pc_40ce;
        case 0x40cf: goto pc_40cf;
        case 0x40d0: goto pc_40d0;
        case 0x40d1: goto pc_40d1;
        case 0x40d2: goto pc_40d2;
        case 0x40d3: goto pc_40d3;
        case 0x40d5: goto pc_40d5;
        case 0x40d6: goto pc_40d6;
        case 0x40d7: goto loc_11_40d7;
        case 0x40d8: goto loc_11_40d8;
        case 0x40d9: goto loc_11_40d9;
        case 0x40da: goto pc_40da;
        case 0x40db: goto pc_40db;
        case 0x40de: goto loc_11_40de;
        case 0x40df: goto pc_40df;
        case 0x40e0: goto pc_40e0;
        case 0x40e1: goto pc_40e1;
        case 0x40e2: goto pc_40e2;
        case 0x40e3: goto pc_40e3;
        case 0x40e4: goto pc_40e4;
        case 0x40e5: goto pc_40e5;
        case 0x40e6: goto pc_40e6;
        case 0x40e7: goto loc_11_40e7;
        case 0x40e8: goto loc_11_40e8;
        case 0x40e9: goto pc_40e9;
        case 0x40ea: goto pc_40ea;
        case 0x40ed: goto pc_40ed;
        case 0x40ee: goto pc_40ee;
        case 0x40ef: goto pc_40ef;
        case 0x40f0: goto pc_40f0;
        case 0x40f1: goto pc_40f1;
        case 0x40f2: goto pc_40f2;
        case 0x40f3: goto pc_40f3;
        case 0x40f4: goto pc_40f4;
        case 0x40f5: goto pc_40f5;
        case 0x40f6: goto loc_11_40f6;
        case 0x40f7: goto pc_40f7;
        case 0x40f8: goto pc_40f8;
        case 0x40f9: goto pc_40f9;
        case 0x40fa: goto loc_11_40fa;
        case 0x40fb: goto loc_11_40fb;
        case 0x40fc: goto pc_40fc;
        case 0x40fd: goto pc_40fd;
        case 0x40fe: goto loc_11_40fe;
        case 0x40ff: goto pc_40ff;
        case 0x4100: goto loc_11_4100;
        case 0x4101: goto pc_4101;
        case 0x4102: goto loc_11_4102;
        case 0x4103: goto pc_4103;
        case 0x4104: goto loc_11_4104;
        case 0x4105: goto loc_11_4105;
        case 0x4106: goto pc_4106;
        case 0x4107: goto pc_4107;
        case 0x4108: goto pc_4108;
        case 0x4109: goto loc_11_4109;
        case 0x410a: goto pc_410a;
        case 0x410b: goto pc_410b;
        case 0x410c: goto pc_410c;
        case 0x410d: goto pc_410d;
        case 0x410e: goto pc_410e;
        case 0x410f: goto pc_410f;
        case 0x4110: goto loc_11_4110;
        case 0x4112: goto loc_11_4112;
        case 0x4114: goto pc_4114;
        case 0x4115: goto pc_4115;
        case 0x4116: goto pc_4116;
        case 0x4118: goto pc_4118;
        case 0x4119: goto pc_4119;
        case 0x411a: goto pc_411a;
        case 0x411b: goto loc_11_411b;
        case 0x411c: goto pc_411c;
        case 0x411d: goto pc_411d;
        case 0x411e: goto loc_11_411e;
        case 0x411f: goto pc_411f;
        case 0x4120: goto pc_4120;
        case 0x4121: goto pc_4121;
        case 0x4123: goto pc_4123;
        case 0x4124: goto loc_11_4124;
        case 0x4126: goto loc_11_4126;
        case 0x4127: goto loc_11_4127;
        case 0x4128: goto pc_4128;
        case 0x4129: goto pc_4129;
        case 0x412b: goto loc_11_412b;
        case 0x412c: goto pc_412c;
        case 0x412d: goto pc_412d;
        case 0x4130: goto pc_4130;
        case 0x4131: goto pc_4131;
        case 0x4132: goto pc_4132;
        case 0x4133: goto pc_4133;
        case 0x4134: goto pc_4134;
        case 0x4135: goto pc_4135;
        case 0x4136: goto pc_4136;
        case 0x4137: goto pc_4137;
        case 0x4138: goto pc_4138;
        case 0x4139: goto loc_11_4139;
        case 0x413a: goto loc_11_413a;
        case 0x413b: goto pc_413b;
        case 0x413c: goto pc_413c;
        case 0x413d: goto pc_413d;
        default: break;
    }

loc_11_4015:
    /* LD DE,$7851 */
    /* 11:4015 */     ctx->de = 0x7851;
    ctx->pc = 0x4018;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4018; /* fallthrough */
loc_11_4016:
    /* LD D,C */
    /* 11:4016 */     ctx->d = ctx->c;
    ctx->pc = 0x4017;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_4017:
    /* 11:4017 */     ctx->a = ctx->b;
    ctx->pc = 0x4018;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4018:
    /* LD E,B */
    /* 11:4018 */     ctx->e = ctx->b;
    ctx->pc = 0x4019;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4019:
    /* LD DE,$7861 */
    /* 11:4019 */     ctx->de = 0x7861;
    ctx->pc = 0x401c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_401c:
    /* 11:401c */     ctx->e = ctx->b;
    ctx->pc = 0x401d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD DE,$7871 */
pc_401d:
    /* 11:401d */     ctx->de = 0x7871;
    ctx->pc = 0x4020;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4020; /* fallthrough */
loc_11_401e:
    /* LD (HL),C */
    /* 11:401e */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x401f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_401f:
    /* 11:401f */     ctx->a = ctx->b;
    ctx->pc = 0x4020;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4020:
    /* LD E,B */
    /* 11:4020 */     ctx->e = ctx->b;
    ctx->pc = 0x4021;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4021:
    /* RST $38 */
    /* 11:4021 */     gbrt_timed_rst(ctx, 0x38, 0x4022);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4022:
    /* LDH A,(C) */
    /* 11:4022 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x4023;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,H */
pc_4023:
    /* 11:4023 */     ctx->b = ctx->h;
    ctx->pc = 0x4024;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4024:
    /* 11:4024 */     /* NOP */
    ctx->pc = 0x4025;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,D */
pc_4025:
    /* 11:4025 */     ctx->b = ctx->d;
    ctx->pc = 0x4026;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4026:
    /* LD A,B */
    /* 11:4026 */     ctx->a = ctx->b;
    ctx->pc = 0x4027;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4027:
    /* POP AF */
    /* 11:4027 */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x4028;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4028:
    /* OR B */
    /* 11:4028 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x4029;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($09b0),SP */
pc_4029:
    /* 11:4029 */     gb_write16(ctx, 0x09b0, ctx->sp);
    ctx->pc = 0x402c;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR B */
pc_402c:
    /* 11:402c */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x402d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(BC) */
pc_402d:
    /* 11:402d */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x402e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_402e:
    /* RST $38 */
    /* 11:402e */     gbrt_timed_rst(ctx, 0x38, 0x402f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_402f:
    /* POP AF */
    /* 11:402f */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x4030;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4030:
    /* OR B */
    /* 11:4030 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x4031;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
pc_4031:
    /* 11:4031 */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x4032;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR B */
pc_4032:
    /* 11:4032 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x4033;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC C */
pc_4033:
    /* 11:4033 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x4034;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR B */
pc_4034:
    /* 11:4034 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x4035;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_4035:
    /* 11:4035 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x4036;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4036:
    /* 11:4036 */     gbrt_timed_rst(ctx, 0x38, 0x4037);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4037:
    /* OR $24 */
    /* 11:4037 */     gb_or8(ctx, 0x24);
    ctx->pc = 0x4039;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_4039:
    /* 11:4039 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x403a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_403a:
    /* 11:403a */     /* NOP */
    ctx->pc = 0x403b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f2 */
pc_403b:
    /* 11:403b */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x403d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_403d:
    /* 11:403d */     gbrt_timed_rst(ctx, 0x0, 0x403e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_403e; /* fallthrough */
loc_11_4038:
    /* INC H */
    /* 11:4038 */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x4039;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
    /* 11:4039 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x403a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 11:403a */     /* NOP */
    ctx->pc = 0x403b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f2 */
    /* 11:403b */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x403d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:403d */     gbrt_timed_rst(ctx, 0x0, 0x403e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_403e; /* fallthrough */
loc_11_403c:
    /* LDH A,(C) */
    /* 11:403c */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x403d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:403d */     gbrt_timed_rst(ctx, 0x0, 0x403e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_403e:
    /* INC B */
    /* 11:403e */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x403f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_403f:
    /* 11:403f */     gb_rrca(ctx);
    ctx->pc = 0x4040;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4040:
    /* INC D */
    /* 11:4040 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x4041;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4041:
    /* CP $f2 */
    /* 11:4041 */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x4043;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_4043:
    /* 11:4043 */     gbrt_timed_rst(ctx, 0x0, 0x4044);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_4044; /* fallthrough */
loc_11_4042:
    /* LDH A,(C) */
    /* 11:4042 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x4043;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:4043 */     gbrt_timed_rst(ctx, 0x0, 0x4044);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4044:
    /* INC B */
    /* 11:4044 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4045;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4045:
    /* 11:4045 */     gb_rrca(ctx);
    ctx->pc = 0x4046;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_4046:
    /* 11:4046 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x4047;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f2 */
pc_4047:
    /* 11:4047 */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x4049;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_4049:
    /* 11:4049 */     gbrt_timed_rst(ctx, 0x0, 0x404a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_404a; /* fallthrough */
loc_11_4048:
    /* LDH A,(C) */
    /* 11:4048 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x4049;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:4049 */     gbrt_timed_rst(ctx, 0x0, 0x404a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_404a:
    /* INC B */
    /* 11:404a */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x404b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_404b:
    /* RRCA */
    /* 11:404b */     gb_rrca(ctx);
    ctx->pc = 0x404c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_404c:
    /* 11:404c */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x404d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f2 */
pc_404d:
    /* 11:404d */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x404f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_404f:
    /* 11:404f */     gbrt_timed_rst(ctx, 0x0, 0x4050);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_4050; /* fallthrough */
loc_11_404e:
    /* LDH A,(C) */
    /* 11:404e */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x404f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:404f */     gbrt_timed_rst(ctx, 0x0, 0x4050);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4050:
    /* CP H */
    /* 11:4050 */     gb_cp8(ctx, ctx->h);
    ctx->pc = 0x4051;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_4051:
    /* 11:4051 */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x4052;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_4052:
    /* 11:4052 */     ctx->pc = 0x4054;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LDH A,(C) */
pc_4054:
    /* 11:4054 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x4055;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4055:
    /* RST $00 */
    /* 11:4055 */     gbrt_timed_rst(ctx, 0x0, 0x4056);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4056:
    /* AND B */
    /* 11:4056 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x4057;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4057:
    /* LD B,$10 */
    /* 11:4057 */     ctx->b = 0x10;
    ctx->pc = 0x4059;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4059; /* fallthrough */
loc_11_4058:
    /* STOP */
    /* 11:4058 */     ctx->pc = 0x405a;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_405a; /* fallthrough */
loc_11_4059:
    /* CP $f2 */
    /* 11:4059 */     gb_cp8(ctx, 0xf2);
    ctx->pc = 0x405b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_405b:
    /* 11:405b */     gbrt_timed_rst(ctx, 0x0, 0x405c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_11_405c; /* fallthrough */
loc_11_405a:
    /* LDH A,(C) */
    /* 11:405a */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x405b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
    /* 11:405b */     gbrt_timed_rst(ctx, 0x0, 0x405c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_405c:
    /* LD ($1006),SP */
    /* 11:405c */     gb_write16(ctx, 0x1006, ctx->sp);
    ctx->pc = 0x405f;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_405f:
    /* CP $f7 */
    /* 11:405f */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x4061;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4061; /* fallthrough */
loc_11_4060:
    /* RST $30 */
    /* 11:4060 */     gbrt_timed_rst(ctx, 0x30, 0x4061);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4061:
    /* INC BC */
    /* 11:4061 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4062;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4062:
    /* 11:4062 */     ctx->e = ctx->c;
    ctx->pc = 0x4063;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4063:
    /* RLCA */
    /* 11:4063 */     gb_rlca(ctx);
    ctx->pc = 0x4064;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,120 */
pc_4064:
    /* 11:4064 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x40de, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40de;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4066, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4066:
    /* LD E,C */
    /* 11:4066 */     ctx->e = ctx->c;
    ctx->pc = 0x4067;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($4858),SP */
pc_4067:
    /* 11:4067 */     gb_write16(ctx, 0x4858, ctx->sp);
    ctx->pc = 0x406a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_406a:
    /* 11:406a */     ctx->e = ctx->c;
    ctx->pc = 0x406b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_406b:
    /* ADD HL,BC */
    /* 11:406b */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x406c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_406c:
    /* 11:406c */     ctx->e = ctx->b;
    ctx->pc = 0x406d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR B */
pc_406d:
    /* 11:406d */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x406e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+40 */
pc_406e:
    /* 11:406e */     gbrt_timed_ld_hl_sp_n(ctx, 0x406f);
    ctx->pc = 0x4070;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4070:
    /* 11:4070 */     /* NOP */
    ctx->pc = 0x4071;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4071; /* fallthrough */
loc_11_406f:
    /* JR Z,0 */
    /* 11:406f */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4071, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4071;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4071, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4071:
    /* LD B,(HL) */
    /* 11:4071 */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4072;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,0 */
pc_4072:
    /* 11:4072 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4074, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4074;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4074, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4074:
    /* LD H,A */
    /* 11:4074 */     ctx->h = ctx->a;
    ctx->pc = 0x4075;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
pc_4075:
    /* 11:4075 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x4077;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4077; /* fallthrough */
loc_11_4076:
    /* RST $30 */
    /* 11:4076 */     gbrt_timed_rst(ctx, 0x30, 0x4077);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4077:
    /* INC BC */
    /* 11:4077 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4078;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4078:
    /* 11:4078 */     ctx->e = ctx->c;
    ctx->pc = 0x4079;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_4079:
    /* 11:4079 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x407a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_407a:
    /* 11:407a */     ctx->e = ctx->b;
    ctx->pc = 0x407b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_407b:
    /* 11:407b */     ctx->c = ctx->b;
    ctx->pc = 0x407c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_407c:
    /* 11:407c */     ctx->e = ctx->c;
    ctx->pc = 0x407d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$58 */
pc_407d:
    /* 11:407d */     ctx->b = 0x58;
    ctx->pc = 0x407f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR B */
pc_407f:
    /* 11:407f */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x4080;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4080:
    /* LD HL,SP+40 */
    /* 11:4080 */     gbrt_timed_ld_hl_sp_n(ctx, 0x4081);
    ctx->pc = 0x4082;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4082:
    /* 11:4082 */     /* NOP */
    ctx->pc = 0x4083;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4083; /* fallthrough */
loc_11_4081:
    /* JR Z,0 */
    /* 11:4081 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4083, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4083;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4083, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4083:
    /* LD B,(HL) */
    /* 11:4083 */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4084;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,0 */
pc_4084:
    /* 11:4084 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4086, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4086;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4086, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4086:
    /* LD H,A */
    /* 11:4086 */     ctx->h = ctx->a;
    ctx->pc = 0x4087;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f6 */
pc_4087:
    /* 11:4087 */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x4089;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_4089:
    /* 11:4089 */     ctx->h = ctx->h;
    ctx->pc = 0x408a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_408a; /* fallthrough */
loc_11_4088:
    /* OR $64 */
    /* 11:4088 */     gb_or8(ctx, 0x64);
    ctx->pc = 0x408a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_408a:
    /* SCF */
    /* 11:408a */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x408b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_408b:
    /* 11:408b */     /* NOP */
    ctx->pc = 0x408c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f6 */
pc_408c:
    /* 11:408c */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x408e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,54 */
pc_408e:
    /* 11:408e */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x40c6, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40c6;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4090, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4090:
    /* NOP */
    /* 11:4090 */     /* NOP */
    ctx->pc = 0x4091;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f6 */
pc_4091:
    /* 11:4091 */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x4093;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4093:
    /* ADD A,B */
    /* 11:4093 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x4094;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4094:
    /* 11:4094 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4096;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f6 */
pc_4096:
    /* 11:4096 */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x4098;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4098; /* fallthrough */
loc_11_4097:
    /* OR $60 */
    /* 11:4097 */     gb_or8(ctx, 0x60);
    ctx->pc = 0x4099;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4099; /* fallthrough */
loc_11_4098:
    /* LD H,B */
    /* 11:4098 */     ctx->h = ctx->b;
    ctx->pc = 0x4099;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4099:
    /* LD (HL),$00 */
    /* 11:4099 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x409b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_409b; /* fallthrough */
loc_11_409a:
    /* NOP */
    /* 11:409a */     /* NOP */
    ctx->pc = 0x409b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_409b:
    /* OR $20 */
    /* 11:409b */     gb_or8(ctx, 0x20);
    ctx->pc = 0x409d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_409d:
    /* 11:409d */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x409e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_409e:
    /* 11:409e */     /* NOP */
    ctx->pc = 0x409f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f8 */
pc_409f:
    /* 11:409f */     gb_cp8(ctx, 0xf8);
    ctx->pc = 0x40a1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,0 */
pc_40a1:
    /* 11:40a1 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x40a3, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40a3;
    } /* Z */
    gbrt_timed_jump(ctx, 0x40a3, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40a3; /* fallthrough */
loc_11_40a0:
    /* LD HL,SP+40 */
    /* 11:40a0 */     gbrt_timed_ld_hl_sp_n(ctx, 0x40a1);
    ctx->pc = 0x40a2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40a2:
    /* 11:40a2 */     /* NOP */
    ctx->pc = 0x40a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40a3:
    /* LD B,E */
    /* 11:40a3 */     ctx->b = ctx->e;
    ctx->pc = 0x40a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,0 */
pc_40a4:
    /* 11:40a4 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x40a6, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40a6;
    } /* Z */
    gbrt_timed_jump(ctx, 0x40a6, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40a6:
    /* LD D,(HL) */
    /* 11:40a6 */     gb_tick(ctx, 7);
    ctx->d = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x40a7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40a7:
    /* CP $f9 */
    /* 11:40a7 */     gb_cp8(ctx, 0xf9);
    ctx->pc = 0x40a9;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0127 */
pc_40a9:
    /* 11:40a9 */     ctx->bc = 0x0127;
    ctx->pc = 0x40ac;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40ac:
    /* 11:40ac */     /* NOP */
    ctx->pc = 0x40ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40ad; /* fallthrough */
loc_11_40a8:
    /* LD SP,HL */
    /* 11:40a8 */     ctx->sp = ctx->hl;
    ctx->pc = 0x40a9;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0127 */
    /* 11:40a9 */     ctx->bc = 0x0127;
    ctx->pc = 0x40ac;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 11:40ac */     /* NOP */
    ctx->pc = 0x40ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40ad:
    /* JR 56 */
    /* 11:40ad */     gbrt_timed_jump(ctx, 0x40e7, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40e7;
    if (ctx->single_step_mode) return;
loc_11_40b0:
    /* RST $30 */
    /* 11:40b0 */     gbrt_timed_rst(ctx, 0x30, 0x40b1);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40b1:
    /* LD (BC),A */
    /* 11:40b1 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x40b2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_40b2:
    /* 11:40b2 */     ctx->e = ctx->c;
    ctx->pc = 0x40b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_40b3:
    /* 11:40b3 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x40b4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_40b4:
    /* 11:40b4 */     ctx->a = ctx->b;
    ctx->pc = 0x40b5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,B */
pc_40b5:
    /* 11:40b5 */     gb_adc8(ctx, ctx->b);
    ctx->pc = 0x40b6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
pc_40b6:
    /* 11:40b6 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x40b8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40b8; /* fallthrough */
loc_11_40b7:
    /* RST $30 */
    /* 11:40b7 */     gbrt_timed_rst(ctx, 0x30, 0x40b8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40b8:
    /* NOP */
    /* 11:40b8 */     /* NOP */
    ctx->pc = 0x40b9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR C,0 */
pc_40b9:
    /* 11:40b9 */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0x40bb, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40bb;
    } /* C */
    gbrt_timed_jump(ctx, 0x40bb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40bb:
    /* LD C,B */
    /* 11:40bb */     ctx->c = ctx->b;
    ctx->pc = 0x40bc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_40bc:
    /* 11:40bc */     ctx->a = ctx->b;
    ctx->pc = 0x40bd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
pc_40bd:
    /* 11:40bd */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x40bf;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40bf; /* fallthrough */
loc_11_40be:
    /* RST $30 */
    /* 11:40be */     gbrt_timed_rst(ctx, 0x30, 0x40bf);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40bf:
    /* LD (BC),A */
    /* 11:40bf */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x40c0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40c0:
    /* LD E,C */
    /* 11:40c0 */     ctx->e = ctx->c;
    ctx->pc = 0x40c1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40c1:
    /* 11:40c1 */     /* NOP */
    ctx->pc = 0x40c2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_40c2:
    /* 11:40c2 */     ctx->e = ctx->b;
    ctx->pc = 0x40c3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40c3:
    /* JR C,-2 */
    /* 11:40c3 */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0x40c3, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40c3;
    } /* C */
    gbrt_timed_jump(ctx, 0x40c5, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40c5:
    /* RST $30 */
    /* 11:40c5 */     gbrt_timed_rst(ctx, 0x30, 0x40c6);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40c6:
    /* NOP */
    /* 11:40c6 */     /* NOP */
    ctx->pc = 0x40c7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_40c7:
    /* 11:40c7 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x40c8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$c828 */
pc_40c8:
    /* 11:40c8 */     ctx->bc = GB_WRAM0_BASE + 0x0828;
    ctx->pc = 0x40cb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40cb; /* fallthrough */
loc_11_40c9:
    /* JR Z,-56 */
    /* 11:40c9 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4093, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4093;
    } /* Z */
    gbrt_timed_jump(ctx, 0x40cb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40cb:
    /* INC (HL) */
    /* 11:40cb */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40cc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40cc:
    /* 11:40cc */     /* NOP */
    ctx->pc = 0x40cd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_40cd:
    /* 11:40cd */     ctx->a = ctx->b;
    ctx->pc = 0x40ce;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,B */
pc_40ce:
    /* 11:40ce */     gb_sbc8(ctx, ctx->b);
    ctx->pc = 0x40cf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_40cf:
    /* 11:40cf */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40d0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40d0:
    /* 11:40d0 */     /* NOP */
    ctx->pc = 0x40d1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,B */
pc_40d1:
    /* 11:40d1 */     gb_adc8(ctx, ctx->b);
    ctx->pc = 0x40d2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,B */
pc_40d2:
    /* 11:40d2 */     gb_sbc8(ctx, ctx->b);
    ctx->pc = 0x40d3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR $44 */
pc_40d3:
    /* 11:40d3 */     gb_or8(ctx, 0x44);
    ctx->pc = 0x40d5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_40d5:
    /* 11:40d5 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x40d6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40d6:
    /* 11:40d6 */     /* NOP */
    ctx->pc = 0x40d7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40d7:
    /* CP $f7 */
    /* 11:40d7 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x40d9;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40d9; /* fallthrough */
loc_11_40d8:
    /* RST $30 */
    /* 11:40d8 */     gbrt_timed_rst(ctx, 0x30, 0x40d9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40d9:
    /* NOP */
    /* 11:40d9 */     /* NOP */
    ctx->pc = 0x40da;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_40da:
    /* 11:40da */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x40db;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$a818 */
pc_40db:
    /* 11:40db */     ctx->bc = GB_ERAM_BASE + 0x0818;
    ctx->pc = 0x40de;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40de:
    /* INC (HL) */
    /* 11:40de */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40df;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40df:
    /* 11:40df */     /* NOP */
    ctx->pc = 0x40e0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_40e0:
    /* 11:40e0 */     ctx->e = ctx->b;
    ctx->pc = 0x40e1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_40e1:
    /* 11:40e1 */     ctx->l = ctx->b;
    ctx->pc = 0x40e2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_40e2:
    /* 11:40e2 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40e3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40e3:
    /* 11:40e3 */     /* NOP */
    ctx->pc = 0x40e4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_40e4:
    /* 11:40e4 */     ctx->e = ctx->b;
    ctx->pc = 0x40e5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR B */
pc_40e5:
    /* 11:40e5 */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x40e6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
pc_40e6:
    /* 11:40e6 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x40e8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40e8; /* fallthrough */
loc_11_40e7:
    /* RST $30 */
    /* 11:40e7 */     gbrt_timed_rst(ctx, 0x30, 0x40e8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_40e8:
    /* NOP */
    /* 11:40e8 */     /* NOP */
    ctx->pc = 0x40e9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_40e9:
    /* 11:40e9 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x40ea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$d878 */
pc_40ea:
    /* 11:40ea */     ctx->bc = GB_WRAMX_BASE + 0x0878;
    ctx->pc = 0x40ed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_40ed:
    /* 11:40ed */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40ee;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40ee:
    /* 11:40ee */     /* NOP */
    ctx->pc = 0x40ef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_40ef:
    /* 11:40ef */     ctx->e = ctx->b;
    ctx->pc = 0x40f0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_40f0:
    /* 11:40f0 */     ctx->c = ctx->b;
    ctx->pc = 0x40f1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_40f1:
    /* 11:40f1 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x40f2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40f2:
    /* 11:40f2 */     /* NOP */
    ctx->pc = 0x40f3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_40f3:
    /* 11:40f3 */     ctx->e = ctx->b;
    ctx->pc = 0x40f4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_40f4:
    /* 11:40f4 */     ctx->l = ctx->b;
    ctx->pc = 0x40f5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f6 */
pc_40f5:
    /* 11:40f5 */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x40f7;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_40f7:
    /* 11:40f7 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x40f8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_40f8:
    /* 11:40f8 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x40f9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40f9:
    /* 11:40f9 */     /* NOP */
    ctx->pc = 0x40fa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40fa; /* fallthrough */
loc_11_40f6:
    /* OR $80 */
    /* 11:40f6 */     gb_or8(ctx, 0x80);
    ctx->pc = 0x40f8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
    /* 11:40f8 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x40f9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 11:40f9 */     /* NOP */
    ctx->pc = 0x40fa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40fa:
    /* CP $f6 */
    /* 11:40fa */     gb_cp8(ctx, 0xf6);
    ctx->pc = 0x40fc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_40fc:
    /* 11:40fc */     ctx->h = ctx->h;
    ctx->pc = 0x40fd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_40fd:
    /* 11:40fd */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x40fe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40fe; /* fallthrough */
loc_11_40fb:
    /* OR $64 */
    /* 11:40fb */     gb_or8(ctx, 0x64);
    ctx->pc = 0x40fd;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
    /* 11:40fd */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x40fe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_40fe:
    /* NOP */
    /* 11:40fe */     /* NOP */
    ctx->pc = 0x40ff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $30 */
pc_40ff:
    /* 11:40ff */     gbrt_timed_rst(ctx, 0x30, 0x4100);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4100:
    /* NOP */
    /* 11:4100 */     /* NOP */
    ctx->pc = 0x4101;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_4101:
    /* 11:4101 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x4102;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4102:
    /* NOP */
    /* 11:4102 */     /* NOP */
    ctx->pc = 0x4103;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,-88 */
pc_4103:
    /* 11:4103 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x40ad, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_40ad;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4105, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_4105; /* fallthrough */
loc_11_4104:
    /* XOR B */
    /* 11:4104 */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x4105;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4105:
    /* LD A,(HL-) */
    /* 11:4105 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x4106;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4106:
    /* 11:4106 */     /* NOP */
    ctx->pc = 0x4107;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_4107:
    /* 11:4107 */     ctx->l = ctx->b;
    ctx->pc = 0x4108;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET Z */
pc_4108:
    /* 11:4108 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4109, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4109:
    /* INC (HL) */
    /* 11:4109 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x410a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_410a:
    /* 11:410a */     /* NOP */
    ctx->pc = 0x410b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_410b:
    /* 11:410b */     ctx->c = ctx->b;
    ctx->pc = 0x410c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_410c:
    /* 11:410c */     ctx->e = ctx->b;
    ctx->pc = 0x410d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_410d:
    /* 11:410d */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x410e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_410e:
    /* 11:410e */     /* NOP */
    ctx->pc = 0x410f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_410f:
    /* 11:410f */     ctx->l = ctx->b;
    ctx->pc = 0x4110;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4110:
    /* JR Z,-2 */
    /* 11:4110 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4110, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4110;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4112, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4112:
    /* OR $44 */
    /* 11:4112 */     gb_or8(ctx, 0x44);
    ctx->pc = 0x4114;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_4114:
    /* 11:4114 */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x4115;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4115:
    /* 11:4115 */     /* NOP */
    ctx->pc = 0x4116;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR $40 */
pc_4116:
    /* 11:4116 */     gb_or8(ctx, 0x40);
    ctx->pc = 0x4118;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_4118:
    /* 11:4118 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4119;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4119:
    /* 11:4119 */     /* NOP */
    ctx->pc = 0x411a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f8 */
pc_411a:
    /* 11:411a */     gb_cp8(ctx, 0xf8);
    ctx->pc = 0x411c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC H */
pc_411c:
    /* 11:411c */     ctx->h = gb_dec8(ctx, ctx->h);
    ctx->pc = 0x411d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_411d:
    /* 11:411d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x411e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_411e; /* fallthrough */
loc_11_411b:
    /* LD HL,SP+37 */
    /* 11:411b */     gbrt_timed_ld_hl_sp_n(ctx, 0x411c);
    ctx->pc = 0x411d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
    /* 11:411d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x411e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_411e:
    /* INC H */
    /* 11:411e */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x411f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC H */
pc_411f:
    /* 11:411f */     ctx->h = gb_dec8(ctx, ctx->h);
    ctx->pc = 0x4120;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4120:
    /* 11:4120 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4121;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,$25 */
pc_4121:
    /* 11:4121 */     ctx->h = 0x25;
    ctx->pc = 0x4123;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4123:
    /* 11:4123 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4124;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4124:
    /* JR Z,-2 */
    /* 11:4124 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4124, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_11_4124;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4126, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_11_4126:
    /* RST $30 */
    /* 11:4126 */     gbrt_timed_rst(ctx, 0x30, 0x4127);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_4127:
    /* NOP */
    /* 11:4127 */     /* NOP */
    ctx->pc = 0x4128;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_4128:
    /* 11:4128 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4129;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$7818 */
pc_4129:
    /* 11:4129 */     ctx->bc = 0x7818;
    ctx->pc = 0x412c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_412c:
    /* 11:412c */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x412d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$d888 */
pc_412d:
    /* 11:412d */     ctx->bc = GB_WRAMX_BASE + 0x0888;
    ctx->pc = 0x4130;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_4130:
    /* 11:4130 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4131;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4131:
    /* 11:4131 */     /* NOP */
    ctx->pc = 0x4132;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_4132:
    /* 11:4132 */     ctx->e = ctx->b;
    ctx->pc = 0x4133;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_4133:
    /* 11:4133 */     ctx->e = ctx->b;
    ctx->pc = 0x4134;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_4134:
    /* 11:4134 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4135;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4135:
    /* 11:4135 */     /* NOP */
    ctx->pc = 0x4136;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_4136:
    /* 11:4136 */     ctx->e = ctx->b;
    ctx->pc = 0x4137;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_4137:
    /* 11:4137 */     ctx->l = ctx->b;
    ctx->pc = 0x4138;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
pc_4138:
    /* 11:4138 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x413a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_413a; /* fallthrough */
loc_11_412b:
    /* LD A,B */
    /* 11:412b */     ctx->a = ctx->b;
    ctx->pc = 0x412c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
    /* 11:412c */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x412d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$d888 */
    /* 11:412d */     ctx->bc = GB_WRAMX_BASE + 0x0888;
    ctx->pc = 0x4130;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
    /* 11:4130 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4131;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 11:4131 */     /* NOP */
    ctx->pc = 0x4132;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
    /* 11:4132 */     ctx->e = ctx->b;
    ctx->pc = 0x4133;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
    /* 11:4133 */     ctx->e = ctx->b;
    ctx->pc = 0x4134;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
    /* 11:4134 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4135;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 11:4135 */     /* NOP */
    ctx->pc = 0x4136;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
    /* 11:4136 */     ctx->e = ctx->b;
    ctx->pc = 0x4137;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
    /* 11:4137 */     ctx->l = ctx->b;
    ctx->pc = 0x4138;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $f7 */
    /* 11:4138 */     gb_cp8(ctx, 0xf7);
    ctx->pc = 0x413a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_413a; /* fallthrough */
loc_11_4139:
    /* RST $30 */
    /* 11:4139 */     gbrt_timed_rst(ctx, 0x30, 0x413a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_413a:
    /* NOP */
    /* 11:413a */     /* NOP */
    ctx->pc = 0x413b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC (HL) */
pc_413b:
    /* 11:413b */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x413c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_413c:
    /* 11:413c */     /* NOP */
    ctx->pc = 0x413d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR -104 */
pc_413d:
    /* 11:413d */     gbrt_timed_jump(ctx, 0x40d7, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_40d7;
    if (ctx->single_step_mode) return;
}

void func_11_4015(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4016(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4018(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4019(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_401e(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4020(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4021(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4026(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4027(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4028(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_402e(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4030(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4038(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_403c(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_403e(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4040(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4041(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4042(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4048(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_404b(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_404e(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4050(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4055(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4057(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4058(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4059(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_405a(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_405c(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_405f(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4060(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4063(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_406b(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_406f(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4076(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4080(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4081(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4088(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_408a(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4097(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4098(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4099(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_409a(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_409b(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40a0(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40a7(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40a8(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40b0(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40b7(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40b8(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40be(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40c0(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40c5(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40c9(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40d8(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40e7(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40f6(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40fa(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40fb(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_40fe(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4102(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4104(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4105(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4110(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_411b(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_411e(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4124(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4126(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_412b(GBContext* ctx) {
    body_11_4015(ctx);
}

void func_11_4139(GBContext* ctx) {
    body_11_4015(ctx);
}

