/* Generated by gbrecomp */
#ifndef Legend_of_Zelda__The___Oracle_of_seasons__USA__H
#define Legend_of_Zelda__The___Oracle_of_seasons__USA__H

#include "gbrt.h"

const GBConfig* Legend_of_Zelda__The___Oracle_of_seasons__USA__default_config(void);
void Legend_of_Zelda__The___Oracle_of_seasons__USA__run(GBContext* ctx);
void Legend_of_Zelda__The___Oracle_of_seasons__USA__init(GBContext* ctx);
int Legend_of_Zelda__The___Oracle_of_seasons__USA__main(int argc, char* argv[]);

#endif
